on:
    push:
      branches:
        - '**'
  
jobs:
    deployment:
      runs-on: ubuntu-latest
      environment: production
      steps:
        - name: deploy
          run: |
            echo "Deploying to production"
            echo "Deployment complete"
        - name: Update deployment status
          run: |
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/siliconraptor/test-github-app/deployments/1/statuses \
            -d '{"environment":"production","state":"success","log_url":"","description":"Deployment finished successfully."}'
      
